field: 0d1d3396-4421-42e8-85bd-cb65e886c293 # Benefits matrix
fieldLayouts:
  b0ed0582-8eeb-4448-8d47-6ad5d5ca51c6:
    tabs:
      -
        elements:
          -
            fieldUid: 2f7f35e2-38a7-45f4-9a1b-cbdb84e72ae0
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: acf421ad-05b0-4496-a152-aa4784ffbc14
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  2f7f35e2-38a7-45f4-9a1b-cbdb84e72ae0:
    contentColumnType: text
    fieldGroup: null
    handle: benefit
    instructions: ''
    name: Benefit
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  acf421ad-05b0-4496-a152-aa4784ffbc14:
    contentColumnType: text
    fieldGroup: null
    handle: icon
    instructions: ''
    name: 'Benefit icon'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: benefits
name: Benefits
sortOrder: 1
