field: 0d1d3396-4421-42e8-85bd-cb65e886c293
fieldLayouts:
  b0ed0582-8eeb-4448-8d47-6ad5d5ca51c6:
    tabs:
      -
        elements:
          -
            fieldUid: c72e1853-746d-4183-8f9c-525bc6f135c9
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 2f7f35e2-38a7-45f4-9a1b-cbdb84e72ae0
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  2f7f35e2-38a7-45f4-9a1b-cbdb84e72ae0:
    contentColumnType: text
    fieldGroup: null
    handle: benefit
    instructions: ''
    name: Benefit
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  c72e1853-746d-4183-8f9c-525bc6f135c9:
    contentColumnType: string
    fieldGroup: null
    handle: icon
    instructions: ''
    name: Icon
    searchable: false
    settings:
      optgroups: true
      options:
        -
          __assoc__:
            -
              - label
              - Shield
            -
              - value
              - 'fal fa-shield-alt'
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Checklist
            -
              - value
              - 'fal fa-tasks'
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Expand
            -
              - value
              - 'fal fa-expand-arrows'
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Sync
            -
              - value
              - 'fal fa-sync'
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
handle: benefits
name: Benefits
sortOrder: 1
