field: 84f72373-7818-40d1-94a1-7bed11823504
fieldLayouts:
  0c58b4f1-8532-4e29-9842-d846675936f3:
    tabs:
      -
        elements:
          -
            fieldUid: 23a7fb42-37f8-4eea-abc6-69628f409e72
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: fc8b508d-d68a-4128-ad01-084b7e0d986f
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: b53003da-07dd-4324-a6f6-bcf4e52ecd8e
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 21112316-603d-48d4-b595-455d750a2ef2
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  21112316-603d-48d4-b595-455d750a2ef2:
    contentColumnType: string
    fieldGroup: null
    handle: itemsPerRow
    instructions: ''
    name: 'Items per row'
    searchable: false
    settings:
      optgroups: true
      options:
        -
          __assoc__:
            -
              - label
              - '6'
            -
              - value
              - '6'
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - '5'
            -
              - value
              - '5'
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - '4'
            -
              - value
              - '4'
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - '3'
            -
              - value
              - '3'
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - '2'
            -
              - value
              - '2'
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  23a7fb42-37f8-4eea-abc6-69628f409e72:
    contentColumnType: text
    fieldGroup: null
    handle: galleryTitle
    instructions: ''
    name: 'Gallery title'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  b53003da-07dd-4324-a6f6-bcf4e52ecd8e:
    contentColumnType: string
    fieldGroup: null
    handle: galleryImages
    instructions: ''
    name: 'Gallery images'
    searchable: false
    settings:
      allowSelfRelations: false
      allowUploads: true
      allowedKinds:
        - image
      defaultUploadLocationSource: 'volume:a6e1cc63-ec74-4588-9aab-3144ee60307e'
      defaultUploadLocationSubpath: ''
      limit: ''
      localizeRelations: false
      previewMode: full
      restrictFiles: '1'
      selectionLabel: ''
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      singleUploadLocationSource: 'volume:a6e1cc63-ec74-4588-9aab-3144ee60307e'
      singleUploadLocationSubpath: ''
      source: null
      sources: '*'
      targetSiteId: null
      useSingleFolder: false
      validateRelatedElements: false
      viewMode: large
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  fc8b508d-d68a-4128-ad01-084b7e0d986f:
    contentColumnType: text
    fieldGroup: null
    handle: galleryIntro
    instructions: ''
    name: 'Gallery intro'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: '1'
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: gallery
name: Gallery
sortOrder: 5
