field: ea214855-af90-41b4-b50f-59f85b4ac9f0 # Product page builder
fieldLayouts:
  9ca7f37a-c3e9-4f7a-9dd3-e82fa4b6d05d:
    tabs:
      -
        elements:
          -
            fieldUid: ec3bcde6-c468-4aed-8441-8b432faa786b # Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 83a6df68-d73d-4d55-bbde-323640eb656a # Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 802e0c5a-9f96-4879-a481-5ab3cc0d2dcf # Background colour
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  802e0c5a-9f96-4879-a481-5ab3cc0d2dcf: # Background colour
    contentColumnType: string
    fieldGroup: null
    handle: backgroundColour
    instructions: ''
    name: 'Background colour'
    searchable: false
    settings:
      optgroups: true
      options:
        -
          __assoc__:
            -
              - label
              - None
            -
              - value
              - ''
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - 'Off white'
            -
              - value
              - bg-off_white
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  83a6df68-d73d-4d55-bbde-323640eb656a: # Text
    contentColumnType: text
    fieldGroup: null
    handle: text
    instructions: ''
    name: Text
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: '1'
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  ec3bcde6-c468-4aed-8441-8b432faa786b: # Heading
    contentColumnType: text
    fieldGroup: null
    handle: heading
    instructions: ''
    name: Heading
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: headingAndText
name: 'Heading and text'
sortOrder: 2
