field: 334c03aa-313f-4dbe-a62a-8c714bd1f30c
fieldLayouts:
  baa61b89-d0d4-4659-8a4d-3003cab63bc4:
    tabs:
      -
        elements:
          -
            fieldUid: c5463cb8-7465-4f11-87c1-e378e237082d
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 97424e57-af03-465d-a9e6-0e3aca03c059
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  97424e57-af03-465d-a9e6-0e3aca03c059:
    contentColumnType: text
    fieldGroup: null
    handle: text
    instructions: ''
    name: Text
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: '1'
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  c5463cb8-7465-4f11-87c1-e378e237082d:
    contentColumnType: text
    fieldGroup: null
    handle: heading
    instructions: ''
    name: Heading
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: headingAndText
name: 'Heading and text'
sortOrder: 2
