field: 84f72373-7818-40d1-94a1-7bed11823504 # Page builder
fieldLayouts:
  5f45d9cf-c4f7-40cf-b9a6-50bb5d890979:
    tabs:
      -
        elements:
          -
            fieldUid: 7e358e6c-31c0-4b58-a4c4-60abe0302443 # Plain text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 46d14d7b-5407-49aa-9b08-aa0b3784938c # Background Colour
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
          -
            fieldUid: e8035954-666e-4499-b592-8095f6a17d61 # Text alignment
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
          -
            fieldUid: b0d9c953-0023-42e0-94d4-fcc464891c0c # Buttons
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  46d14d7b-5407-49aa-9b08-aa0b3784938c: # Background Colour
    contentColumnType: string
    fieldGroup: null
    handle: backgroundColour
    instructions: ''
    name: 'Background Colour'
    searchable: false
    settings:
      optgroups: true
      options:
        -
          __assoc__:
            -
              - label
              - White
            -
              - value
              - bg-white
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - Navy
            -
              - value
              - bg-navy
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Mustard
            -
              - value
              - bg-mustard
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Blue
            -
              - value
              - bg-blue
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  7e358e6c-31c0-4b58-a4c4-60abe0302443: # Plain text
    contentColumnType: text
    fieldGroup: null
    handle: plainText
    instructions: 'Insert your text here in markdown, it is very easy syntax to learn and is available everywhere!'
    name: 'Plain text'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: '1'
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  b0d9c953-0023-42e0-94d4-fcc464891c0c: # Buttons
    contentColumnType: string
    fieldGroup: null
    handle: buttons
    instructions: ''
    name: Buttons
    searchable: false
    settings:
      contentTable: '{{%stc_3_buttons}}'
      fieldLayout: row
      maxRows: ''
      minRows: ''
      placeholderKey: null
      propagationMethod: all
      selectionLabel: ''
      staticField: ''
    translationKeyFormat: null
    translationMethod: site
    type: verbb\supertable\fields\SuperTableField
  e8035954-666e-4499-b592-8095f6a17d61: # Text alignment
    contentColumnType: string
    fieldGroup: null
    handle: textAlignment
    instructions: ''
    name: 'Text alignment'
    searchable: false
    settings:
      optgroups: true
      options:
        -
          __assoc__:
            -
              - label
              - Left
            -
              - value
              - text-left
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - Centre
            -
              - value
              - text-center
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
handle: plainText
name: 'Plain text'
sortOrder: 1
