field: 49804445-f3e7-4a76-818a-5f01de434004
fieldLayouts:
  e4330621-4ceb-423e-8fec-109cad66ff97:
    tabs:
      -
        elements:
          -
            fieldUid: 059586b4-925e-43b0-a789-f6ab889d1a69
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 5f7c0ab2-2d51-4bfc-817a-d822d1dc874e
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  059586b4-925e-43b0-a789-f6ab889d1a69:
    contentColumnType: text
    fieldGroup: null
    handle: relatedProductsText
    instructions: ''
    name: 'Related products text'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: '1'
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  5f7c0ab2-2d51-4bfc-817a-d822d1dc874e:
    contentColumnType: string
    fieldGroup: null
    handle: relatedProducts
    instructions: ''
    name: 'Related products'
    searchable: false
    settings:
      allowSelfRelations: false
      limit: ''
      localizeRelations: false
      selectionLabel: 'Add related products'
      showSiteMenu: true
      source: null
      sources:
        - 'section:6a5d8388-4e65-4388-ad8c-b1ef16476a2c'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Entries
handle: relatedProducts
name: 'Related products'
sortOrder: 1
