field: 84f72373-7818-40d1-94a1-7bed11823504 # Page builder
fieldLayouts:
  e3d32580-176f-446b-b4d2-a5365d33b016:
    tabs:
      -
        elements:
          -
            fieldUid: 18daf619-738b-4576-9cd6-6c76e9587d9c
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: c4f5b69d-0a3c-4f14-a93f-7d4236ba66b8
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
          -
            fieldUid: dfc0d4fc-ef48-49be-9dc7-3c44a5da6d32
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
        name: Content
        sortOrder: 1
fields:
  18daf619-738b-4576-9cd6-6c76e9587d9c:
    contentColumnType: string
    fieldGroup: null
    handle: relatedEntries
    instructions: ''
    name: Entries
    searchable: false
    settings:
      allowSelfRelations: false
      limit: ''
      localizeRelations: false
      selectionLabel: 'Find an entry'
      showSiteMenu: true
      source: null
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Entries
  c4f5b69d-0a3c-4f14-a93f-7d4236ba66b8:
    contentColumnType: string
    fieldGroup: null
    handle: backgroundColour
    instructions: ''
    name: 'Background colour'
    searchable: false
    settings:
      optgroups: true
      options:
        -
          __assoc__:
            -
              - label
              - White
            -
              - value
              - bg-white
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Navy
            -
              - value
              - bg-navy
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Mustard
            -
              - value
              - bg-mustard
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Blue
            -
              - value
              - bg-blue
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  dfc0d4fc-ef48-49be-9dc7-3c44a5da6d32:
    contentColumnType: string
    fieldGroup: null
    handle: layout
    instructions: 'What layout would you like the related entries to have?'
    name: Layout
    searchable: false
    settings:
      optgroups: true
      options:
        -
          __assoc__:
            -
              - label
              - Cards
            -
              - value
              - cards
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - Tiles
            -
              - value
              - tiles
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
handle: relatedEntries
name: 'Related entries'
sortOrder: 2
