field: 84f72373-7818-40d1-94a1-7bed11823504 # Page builder
fieldLayouts:
  77078a5a-9353-4162-bd73-1a863180760f:
    tabs:
      -
        elements:
          -
            fieldUid: c3dfd38a-2354-4654-ac85-1daf800e35f3
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 25
          -
            fieldUid: dcd87c31-8602-4d0b-b36a-de8f51c3cadd
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 25
          -
            fieldUid: 456d6491-f7f6-46ef-9871-b71cf6f8246d
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 25
          -
            fieldUid: 0705587e-3a71-445b-9fdc-f58c9b8f3de8
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 25
          -
            fieldUid: c226b997-c58c-42e9-906a-4089abfa7f5a
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 2e8c2d72-0992-4133-824d-8398f0d80292
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 774a8d88-ebee-4be9-a34b-55d12783d5b1
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
          -
            fieldUid: 60eb1b8a-39c0-4bb4-ab3b-11fa940bfa1d
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
        name: Content
        sortOrder: 1
fields:
  0705587e-3a71-445b-9fdc-f58c9b8f3de8:
    contentColumnType: text
    fieldGroup: null
    handle: idSlug
    instructions: 'This is optional, it is used if you need to link to this particular section, append a # and the slug name, for example mincotech.com.au/about#our-history'
    name: 'ID Slug'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  2e8c2d72-0992-4133-824d-8398f0d80292:
    contentColumnType: string
    fieldGroup: null
    handle: backgroundColour
    instructions: ''
    name: 'Background Colour'
    searchable: false
    settings:
      optgroups: true
      options:
        -
          __assoc__:
            -
              - label
              - White
            -
              - value
              - bg-white
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - Navy
            -
              - value
              - bg-navy
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Mustard
            -
              - value
              - bg-mustard
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Blue
            -
              - value
              - bg-blue
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  456d6491-f7f6-46ef-9871-b71cf6f8246d:
    contentColumnType: string
    fieldGroup: null
    handle: mediaAlignment
    instructions: ''
    name: 'Media alignment'
    searchable: false
    settings:
      optgroups: true
      options:
        -
          __assoc__:
            -
              - label
              - Left
            -
              - value
              - left
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - Right
            -
              - value
              - right
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  60eb1b8a-39c0-4bb4-ab3b-11fa940bfa1d:
    contentColumnType: text
    fieldGroup: null
    handle: linkUrl
    instructions: ''
    name: 'Link URL'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  774a8d88-ebee-4be9-a34b-55d12783d5b1:
    contentColumnType: text
    fieldGroup: null
    handle: linkText
    instructions: ''
    name: 'Link text'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  c226b997-c58c-42e9-906a-4089abfa7f5a:
    contentColumnType: text
    fieldGroup: null
    handle: text
    instructions: ''
    name: Text
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: '1'
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  c3dfd38a-2354-4654-ac85-1daf800e35f3:
    contentColumnType: string
    fieldGroup: null
    handle: image
    instructions: ''
    name: Image
    searchable: false
    settings:
      allowSelfRelations: false
      allowUploads: true
      allowedKinds: null
      defaultUploadLocationSource: 'volume:a6e1cc63-ec74-4588-9aab-3144ee60307e'
      defaultUploadLocationSubpath: ''
      limit: '1'
      localizeRelations: false
      previewMode: full
      restrictFiles: ''
      selectionLabel: 'Add an image'
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      singleUploadLocationSource: 'volume:a6e1cc63-ec74-4588-9aab-3144ee60307e'
      singleUploadLocationSubpath: ''
      source: null
      sources: '*'
      targetSiteId: null
      useSingleFolder: false
      validateRelatedElements: false
      viewMode: large
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  dcd87c31-8602-4d0b-b36a-de8f51c3cadd:
    contentColumnType: string
    fieldGroup: null
    handle: mediaWidth
    instructions: ''
    name: 'Media width'
    searchable: false
    settings:
      optgroups: true
      options:
        -
          __assoc__:
            -
              - label
              - Half
            -
              - value
              - w-1/2
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - Third
            -
              - value
              - w-1/3
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Quarter
            -
              - value
              - w-1/4
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
handle: textAndMedia
name: 'Text and media'
sortOrder: 3
