fieldLayouts:
  ee636ab5-b336-4248-8520-e731916d68b2:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            required: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
      -
        elements:
          -
            fieldUid: 27a6b2f7-125f-4435-89f3-c86ece6fae10
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: d458148a-cac9-4331-8450-c852bb68f250
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 7f92ebb9-d48f-483c-ad92-06b7390a5421
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: e8194a63-8d8f-44d2-a059-2c166d82a4c2
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 751f9ff7-baa1-4994-82a0-653b81eeb5a7
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: SEO
        sortOrder: 2
handle: productCategories
name: 'Product Categories'
siteSettings:
  3cc4705b-9d87-4251-bf19-e831c181126f:
    hasUrls: true
    template: null
    uriFormat: 'product-categories/{slug}'
structure:
  maxLevels: null
  uid: 19a287cb-5536-49f9-b9e1-f8b7c87705cb
