fieldLayouts:
  ee636ab5-b336-4248-8520-e731916d68b2:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            warning: null
            width: 100
          -
            fieldUid: 35652ee1-7486-42f7-962f-d6ae13c4f02f # Product category description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 6421bc18-1f6d-4898-bdb4-528c7af942f4 # Product category page builder
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 0d1d3396-4421-42e8-85bd-cb65e886c293 # Benefits matrix
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            type: craft\fieldlayoutelements\HorizontalRule
          -
            fieldUid: e82be625-ba7e-4423-855d-9a55d0af72a2 # Product overview
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            type: craft\fieldlayoutelements\HorizontalRule
          -
            fieldUid: b1791c9d-e452-4bce-8404-7e8d266ba9fb # Product blockquote
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
      -
        elements:
          -
            fieldUid: 27a6b2f7-125f-4435-89f3-c86ece6fae10 # SEO Title
            instructions: ''
            label: ''
            required: '1'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: d458148a-cac9-4331-8450-c852bb68f250 # SEO Description
            instructions: ''
            label: ''
            required: '1'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 7f92ebb9-d48f-483c-ad92-06b7390a5421 # SEO Image
            instructions: ''
            label: ''
            required: '1'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: e8194a63-8d8f-44d2-a059-2c166d82a4c2 # SEO Image description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 751f9ff7-baa1-4994-82a0-653b81eeb5a7 # SEO Keywords
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: SEO
        sortOrder: 2
handle: productCategories
name: 'Product Categories'
siteSettings:
  3cc4705b-9d87-4251-bf19-e831c181126f: # Mincotech
    hasUrls: true
    template: products/_entry
    uriFormat: 'products/{slug}'
structure:
  maxLevels: null
  uid: 19a287cb-5536-49f9-b9e1-f8b7c87705cb
