fieldLayouts:
  a225e82f-f255-4401-b7fb-5ca05ec675c1:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: uploads
hasUrls: true
name: Uploads
settings:
  bucket: $DO_BUCKET
  contentDisposition: ''
  endpoint: $DO_ENDPOINT
  expires: '3 months'
  keyId: $DO_ACCESS_KEY
  region: $DO_REGION
  secret: $DO_SECRET_KEY
  subfolder: mincotec/assets
sortOrder: 1
type: vaersaagod\dospaces\Volume
url: $DO_BASE_URL
