contentColumnType: string
fieldGroup: fcefe5a5-ffb6-4f9f-84d4-a386f43bd9a5
handle: benefitsMatrix
instructions: ''
name: 'Benefits matrix'
searchable: false
settings:
  contentTable: '{{%matrixcontent_benefitsmatrix}}'
  maxBlocks: ''
  minBlocks: ''
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
