contentColumnType: string
fieldGroup: 066213dd-5fa5-4164-ae9e-f0d636f41d32 # Common
handle: contentPageBuilder
instructions: ''
name: 'Content page builder'
searchable: false
settings:
  contentTable: '{{%matrixcontent_contentpagebuilder}}'
  maxBlocks: ''
  minBlocks: ''
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
