contentColumnType: text
fieldGroup: 1fe3918e-e846-42c8-a2bb-d75a69804c1a # Call to action
handle: formDescription
instructions: ''
name: 'Form description'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: '1'
  placeholder: ''
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
