contentColumnType: string
fieldGroup: 1fe3918e-e846-42c8-a2bb-d75a69804c1a
handle: form
instructions: ''
name: Form
searchable: false
settings:
  allowSelfRelations: false
  limit: '1'
  localizeRelations: false
  selectionLabel: ''
  showSiteMenu: true
  source: null
  sources: '*'
  targetSiteId: null
  validateRelatedElements: false
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: verbb\formie\fields\Forms
