contentColumnType: string
fieldGroup: 94f74fba-62be-4da9-93b4-964abc5e02c5 # Page builder
handle: pageBuilder
instructions: ''
name: 'Page builder'
searchable: false
settings:
  contentTable: '{{%matrixcontent_pagebuilder}}'
  maxBlocks: ''
  minBlocks: ''
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
