contentColumnType: text
fieldGroup: 368b1a7c-711e-4626-897c-c306156ada05
handle: phoneNumber
instructions: ''
name: 'Phone number'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: ''
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
