contentColumnType: string
fieldGroup: fcefe5a5-ffb6-4f9f-84d4-a386f43bd9a5 # Product category fields
handle: productCategoryPageBuilder
instructions: ''
name: 'Product category page builder'
searchable: false
settings:
  contentTable: '{{%matrixcontent_productcategorypagebuilder}}'
  maxBlocks: ''
  minBlocks: ''
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
