contentColumnType: text
fieldGroup: 60d265fe-4e19-4fb7-8444-54d559d58ef3
handle: projectDescription
instructions: ''
name: 'Project description'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: '1'
  placeholder: ''
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
