contentColumnType: string
fieldGroup: 1ec61136-2f61-415d-b611-53f0d990dd34
handle: relatedProducts
instructions: ''
name: 'Related products'
searchable: false
settings:
  contentTable: '{{%matrixcontent_relatedproducts}}'
  maxBlocks: '1'
  minBlocks: '1'
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
