contentColumnType: string
fieldGroup: 1ec61136-2f61-415d-b611-53f0d990dd34 # Resource fields
handle: relatedResource
instructions: ''
name: 'Related resource'
searchable: false
settings:
  allowSelfRelations: false
  limit: ''
  localizeRelations: false
  selectionLabel: 'Relate a resource'
  showSiteMenu: true
  source: null
  sources:
    - 'section:e892d3ce-39c6-4f38-b352-1cdc5d7be1a8' # Resources
  targetSiteId: null
  validateRelatedElements: false
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Entries
