contentColumnType: string
fieldGroup: 066213dd-5fa5-4164-ae9e-f0d636f41d32
handle: relatedEntries
instructions: ''
name: 'Related Entries'
searchable: false
settings:
  contentTable: '{{%matrixcontent_relatedentries}}'
  maxBlocks: ''
  minBlocks: ''
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
