contentColumnType: text
fieldGroup: bd1a122e-69e2-4d18-b94b-59798d4f3041 # SEO
handle: seoKeywords
instructions: 'Include a comma separated list of keywords you''d like search engines to use for this page. Note that Google doesn''t do this anymore but other search engines still do.'
name: 'SEO Keywords'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: ''
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
