dateModified: 1598509407
email:
  fromEmail: ryan@newwordorder.com.au
  fromName: Mincotec
  transportType: craft\mail\transportadapters\Sendmail
system:
  edition: solo
  live: true
  name: Mincotec
  schemaVersion: 3.5.13
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  requireEmailVerification: true
