dateModified: 1618969901
email:
  fromEmail: ryan@newwordorder.com.au
  fromName: Mincotec
  transportType: craft\mail\transportadapters\Sendmail
plugins:
  blitz:
    edition: standard
    enabled: true
    licenseKey: 8VI91HJJZTQP9XOTAMPNFIC6
    schemaVersion: 3.6.6
    settings:
      apiKey: ''
      cacheControlHeader: 'public, s-maxage=31536000, max-age=0'
      cacheDuration: null
      cacheElementQueries: true
      cacheElements: true
      cachePurgerType: putyourlightson\blitz\drivers\purgers\DummyPurger
      cacheStorageSettings:
        __assoc__:
          -
            - folderPath
            - '@webroot/cache/blitz'
          -
            - createGzipFiles
            - ''
      cacheStorageType: putyourlightson\blitz\drivers\storage\FileStorage
      cacheWarmerSettings:
        __assoc__:
          -
            - concurrency
            - '3'
      cacheWarmerType: putyourlightson\blitz\drivers\warmers\GuzzleWarmer
      cachingEnabled: ''
      clearCacheAutomatically: '1'
      customSiteUris: ''
      debug: false
      deployerType: putyourlightson\blitz\drivers\deployers\DummyDeployer
      driverJobPriority: 100
      excludedQueryStringParams:
        - gclid
        - fbclid
      excludedUriPatterns: ''
      includedUriPatterns:
        -
          __assoc__:
            -
              - uriPattern
              - '.*'
      injectScriptEvent: DOMContentLoaded
      integrations:
        - putyourlightson\blitz\drivers\integrations\FeedMeIntegration
        - putyourlightson\blitz\drivers\integrations\SeomaticIntegration
      mutexTimeout: 1
      outputComments: true
      queryStringCaching: '0'
      refreshCacheAutomaticallyForGlobals: true
      refreshCacheJobPriority: 10
      refreshCacheWhenElementSavedNotLive: false
      refreshCacheWhenElementSavedUnchanged: false
      sendPoweredByHeader: true
      warmCacheAutomatically: '1'
  contact-form:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
    settings:
      allowAttachments: ''
      prependSender: 'On behalf of'
      prependSubject: 'New message from Mincotech'
      successFlashMessage: 'Your message has been sent.'
      toEmail: ryan@newwordorder.com.au
  contact-form-extensions:
    edition: standard
    enabled: true
    schemaVersion: 1.0.1
    settings:
      confirmationSubject: ''
      confirmationTemplate: ''
      enableConfirmationEmail: ''
      enableDatabase: '1'
      enableTemplateOverwrite: ''
      notificationTemplate: ''
      recaptcha: ''
      recaptchaDataBadge: bottomright
      recaptchaDebug: ''
      recaptchaHideBadge: ''
      recaptchaSecretKey: ''
      recaptchaSiteKey: ''
      recaptchaThreshold: '0.5'
      recaptchaTimeout: '5'
      recaptchaVersion: ''
  dospaces:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  field-manager:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  freeform:
    edition: pro
    enabled: true
    licenseKey: XUMEF3VK7A85Y6B2IRNCLT6W
    schemaVersion: 3.3.1
    settings:
      ajaxByDefault: true
      alertNotificationRecipients: digital@newwordorder.com.au
      autoScrollToErrors: true
      badgeType: all
      blockedEmails: null
      blockedEmailsError: 'Invalid Email Address'
      blockedIpAddresses: null
      blockedKeywords: null
      blockedKeywordsError: 'Invalid Entry Data'
      clientDigestFrequency: 1
      clientDigestRecipients: digital@newwordorder.com.au
      customErrorMessage: null
      customHoneypotName: null
      defaultTemplates: true
      defaultView: dashboard
      digestFrequency: 1
      digestOnlyOnProduction: false
      digestRecipients: digital@newwordorder.com.au
      displayFeed: true
      emailTemplateDirectory: null
      emailTemplateStorage: db
      fieldDisplayOrder: name
      fillWithGet: false
      footerScripts: false
      formSubmitDisable: true
      formSubmitExpiration: null
      formTemplateDirectory: null
      formattingTemplate: tailwind.html
      freeformHoneypot: true
      freeformHoneypotEnhancement: false
      hideBannerDemo: false
      hideBannerOldFreeform: false
      minimumSubmitTime: null
      pluginName: ''
      purgableSpamAgeInDays: null
      purgableSubmissionAgeInDays: null
      purgableUnfinalizedAssetAgeInMinutes: 180
      recaptchaBehaviour: display_error
      recaptchaEnabled: false
      recaptchaErrorMessage: 'Please verify that you are not a robot.'
      recaptchaKey: null
      recaptchaMinScore: 0.5
      recaptchaSecret: null
      recaptchaSize: normal
      recaptchaTheme: light
      recaptchaType: v2_checkbox
      removeNewlines: false
      renderFormHtmlInCpViews: true
      salesforce_client_id: null
      salesforce_client_secret: null
      salesforce_password: null
      salesforce_username: null
      scriptInsertLocation: footer
      sessionEntryMaxCount: 50
      sessionEntryTTL: 10800
      showErrorsForBlockedEmails: false
      showErrorsForBlockedKeywords: false
      showTutorial: false
      spamFolderEnabled: true
      spamProtectionBehaviour: simulate_success
      submissionThrottlingCount: null
      submissionThrottlingTimeFrame: null
      twigInHtml: true
      twigInHtmlIsolatedMode: true
      updateSearchIndexes: true
  image-optimize:
    edition: standard
    enabled: true
    licenseKey: Z8MSF9L6EB83EB718X6EGGWW
    schemaVersion: 1.0.0
    settings:
      allowUpScaledImageVariants: false
      assetVolumeSubFolders: true
      autoSharpenScaledImages: true
      createColorPalette: true
      createPlaceholderSilhouettes: false
      imageTransformTypeSettings:
        __assoc__:
          -
            - nystudio107\imageoptimizeimgix\imagetransforms\ImgixImageTransform
            -
              __assoc__:
                -
                  - domain
                  - ''
                -
                  - apiKey
                  - ''
                -
                  - securityToken
                  - ''
          -
            - nystudio107\imageoptimizesharp\imagetransforms\SharpImageTransform
            -
              __assoc__:
                -
                  - baseUrl
                  - ''
          -
            - nystudio107\imageoptimizethumbor\imagetransforms\ThumborImageTransform
            -
              __assoc__:
                -
                  - baseUrl
                  - ''
                -
                  - securityKey
                  - ''
      lowerQualityRetinaImageVariants: true
      transformClass: nystudio107\imageoptimize\imagetransforms\CraftImageTransform
  navigation:
    edition: standard
    enabled: true
    licenseKey: 6P9TK7KM2PSXPK8Z9XBEQI7E
    schemaVersion: 1.0.21
  seomatic:
    edition: standard
    enabled: true
    licenseKey: QG5X7OQ8MLM3VR9O0MF1QPW9
    schemaVersion: 3.0.9
  super-table:
    edition: standard
    enabled: true
    schemaVersion: 2.2.1
system:
  edition: pro
  live: true
  name: Mincotech
  retryDuration: null
  schemaVersion: 3.6.8
  timeZone: Australia/Brisbane
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  requireEmailVerification: true
