dateModified: 1604880849
email:
  fromEmail: ryan@newwordorder.com.au
  fromName: Mincotec
  transportType: craft\mail\transportadapters\Sendmail
plugins:
  dospaces:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  field-manager:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  formie:
    edition: standard
    enabled: true
    schemaVersion: 1.0.13
    settings:
      captchas:
        duplicate:
          enabled: false
          settings:
            handle: duplicate
          type: verbb\formie\integrations\captchas\Duplicate
        honeypot:
          enabled: true
          settings:
            handle: honeypot
          type: verbb\formie\integrations\captchas\Honeypot
        javascript:
          enabled: false
          settings:
            handle: javascript
          type: verbb\formie\integrations\captchas\Javascript
        recaptcha:
          enabled: false
          settings:
            badge: bottomright
            handle: recaptcha
            language: en
            minScore: '0.5'
            secretKey: ''
            siteKey: ''
            size: normal
            theme: light
            type: v3
          type: verbb\formie\integrations\captchas\Recaptcha
  image-optimize:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  navigation:
    edition: standard
    enabled: true
    schemaVersion: 1.0.21
  seomatic:
    edition: standard
    enabled: true
    schemaVersion: 3.0.9
system:
  edition: pro
  live: true
  name: Mincotech
  retryDuration: null
  schemaVersion: 3.5.13
  timeZone: Australia/Brisbane
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  requireEmailVerification: true
