dateModified: 1599013857
email:
  fromEmail: ryan@newwordorder.com.au
  fromName: Mincotec
  transportType: craft\mail\transportadapters\Sendmail
plugins:
  dospaces:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  image-optimize:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  seomatic:
    edition: standard
    enabled: true
    schemaVersion: 3.0.9
system:
  edition: pro
  live: true
  name: Mincotec
  schemaVersion: 3.5.13
  timeZone: Australia/Brisbane
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  requireEmailVerification: true
