field: a3c732b0-09bc-4e9e-9bba-3c7bdf5c050b # blocks
fieldLayouts:
  2a6f39f9-e203-4983-8f87-ca0dca6bb52e:
    tabs:
      -
        elements:
          -
            fieldUid: bf58bb6d-252e-4193-9375-6c2d02406232 # Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: fca73b00-6cb6-4ad7-bb7a-b25900f09349 # Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  bf58bb6d-252e-4193-9375-6c2d02406232: # Heading
    contentColumnType: text
    fieldGroup: null
    handle: heading
    instructions: ''
    name: Heading
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  fca73b00-6cb6-4ad7-bb7a-b25900f09349: # Text
    contentColumnType: text
    fieldGroup: null
    handle: text
    instructions: ''
    name: Text
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: '1'
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
