field: b0d9c953-0023-42e0-94d4-fcc464891c0c # Buttons
fieldLayouts:
  abe4c8f5-2d1b-4307-ac44-903744bc3bc7:
    tabs:
      -
        elements:
          -
            fieldUid: 305978ed-0367-4d6e-b99a-6a0593a86670 # Button text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 6326a671-71dc-41b2-a8d6-61356e4543b3 # Button link
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: d7995a8c-0068-4fa0-acc8-7b72aa116a83 # Button colour
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  305978ed-0367-4d6e-b99a-6a0593a86670: # Button text
    contentColumnType: text
    fieldGroup: null
    handle: buttonText
    instructions: ''
    name: 'Button text'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  6326a671-71dc-41b2-a8d6-61356e4543b3: # Button link
    contentColumnType: text
    fieldGroup: null
    handle: buttonLink
    instructions: ''
    name: 'Button link'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  d7995a8c-0068-4fa0-acc8-7b72aa116a83: # Button colour
    contentColumnType: string
    fieldGroup: null
    handle: buttonColour
    instructions: ''
    name: 'Button colour'
    searchable: false
    settings:
      optgroups: true
      options:
        -
          __assoc__:
            -
              - label
              - White
            -
              - value
              - white
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Navy
            -
              - value
              - navy
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
