enableVersioning: true
handle: contact
name: Contact
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  3cc4705b-9d87-4251-bf19-e831c181126f: # Mincotech
    enabledByDefault: true
    hasUrls: true
    template: single/page
    uriFormat: contact
type: single
