enableVersioning: true
handle: products
name: Products
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  3cc4705b-9d87-4251-bf19-e831c181126f:
    enabledByDefault: true
    hasUrls: true
    template: product/_entry
    uriFormat: 'product/{slug}'
structure:
  maxLevels: 1
  uid: 8e6a2c10-0950-4378-b0e9-af07550e830d
type: structure
