enableVersioning: true
handle: projects
name: Projects
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  3cc4705b-9d87-4251-bf19-e831c181126f: # Mincotech
    enabledByDefault: true
    hasUrls: true
    template: null
    uriFormat: 'projects/{slug}'
type: channel
