enableVersioning: true
handle: resources
name: Resources
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  3cc4705b-9d87-4251-bf19-e831c181126f:
    enabledByDefault: true
    hasUrls: true
    template: resource/_entry
    uriFormat: 'resources/{slug}'
structure:
  maxLevels: null
  uid: 9e7f20b8-5851-4551-9907-fab15b110bed
type: structure
