handle: inlineForm
name: 'Inline form'
outputCssLayout: '1'
outputCssLocation: page-header
outputCssTheme: '1'
outputJsBase: '1'
outputJsLocation: page-footer
outputJsTheme: '1'
sortOrder: 99
template: _forms
useCustomTemplates: '1'
